# Generated by Django 3.1.7 on 2021-04-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wishApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=13, unique=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('gifts', models.ManyToManyField(to='wishApp.Gifts')),
                ('recipient_subs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_subs_id', to='wishApp.subscribers')),
                ('sender_subs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_subs_id', to='wishApp.subscribers')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wishApp.wish')),
            ],
        ),
        migrations.CreateModel(
            name='Request_gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wishApp.gifts')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wishApp.requests')),
            ],
        ),
    ]
